name: Cuse of Myrra Certificate Renewal

on:
  push:
    branches:
      - cert-renewal
    
  schedule:
    - cron: '0 0 1 */2 *' # Running at 1st of the month, every two months.

jobs:

  regenerate-certificate:
    name: Renew Certificates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # staging_brasil, staging_europe, testing_brasil, testing_europe
        IP: [ 54.94.12.50, 49.13.65.169, 54.207.194.197, 5.75.237.197]

    steps:

    - name: Create ssh private key file from env var
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        set -ex
        sed -E 's/(-+(BEGIN|END) OPENSSH PRIVATE KEY-+) *| +/\1\n/g' <<< "$SSH_KEY" > id_ed25519
        chmod 400 id_ed25519

    - name: Renew certificates
      env:
        HOST: ${{ matrix.IP }}
      run: |
          set -ex
          ssh -i id_ed25519 root@$HOST -o StrictHostKeyChecking=no certbot renew 
          set +ex
