name: "Stop Brazil instances: testing and staging"
on:
  workflow_dispatch:

jobs:
  stop-brazil-instance:
    name: "Stop Brazil instances: aws-testing.dark-worlds.lambdaclass.com and brazil-staging.curseofmyrra.com"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_BRAZIL_INSTANCE }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_BRAZIL_INSTANCE }}
      AWS_REGION: sa-east-1

    steps:
      - name: Stop Brazil instance
        run: |
          set -ex
          # Stop testing instance
          aws ec2 stop-instances --instance-ids i-0a6c828181e221c1e
          # Stop staging instance
          aws ec2 stop-instances --instance-ids i-03e46e6efd009a6ce
